packages:
  - 'src/web-admin'
  - 'src/web-user'
  - 'src/api'
  - 'src/mobile'
  - 'src/shared'
  - 'src/database'
  # Shared packages from parent monorepo (relative paths)
  - '../../shared/database'
  - '../../shared/api-types'
  - '../../shared/api'